spring:
  datasource:
    username: mechanic_shop
    password: mechanic_shop
    url: jdbc:mysql://localhost:3306/mechanic_shop
    
  jpa:
    hibernate:
      ddl_auto: update
    show_sql: true